### ISSUE TITLE
Add an option to dump the whole dependency graph

### ISSUE THREAD

**Issue by psychon** [mpeterv/depgraph#1]
Hi,

yesterday I stumbled upon this nice tool while investigating https://github.com/awesomeWM/awesome/issues/1400. Our [plan is to have rules about which of our modules may depend on other modules](https://github.com/awesomeWM/awesome/issues/1400#issuecomment-273444696). These rules should somehow be enforced. For this, we need a way to dump module dependencies / require calls.

This is where your nice tool would come in. However, right now there is (as far as I can see) no way to just access/dump all module dependencies.

I see two ways to achieve my goal:

* Write a Lua program that require's depgraph to use it and accesses the information it collects. This could then check for violations of our new rules.
* Extend depgraph so that it can dump all dependencies in some parsable format and then do some shell scripting magic.

Which of the approaches would you prefer? Any pointers on how I should continue?
I would also volunteer for some implementation work. :-)

**Comment by mpeterv** [comment]
Hi @psychon,

I think I like option 1 more. Basically, documenting 'make_graph' function from 'depgraph' module should be enough, but it could also be useful to expose some functions that format dependencies as strings.

**Comment by psychon** [comment]
Implemented (using only `make_graph`): https://github.com/awesomeWM/awesome/commit/0afed66ccf88235aeab0f0a51b68a5151bd311e9
